In [7]:
import pandas as pd
data = pd.read_csv("final_test.csv")
# null
data = data.drop_duplicates()
data.duplicated().sum()



0

In [8]:
data

subject  \
0                     enron methanol ; meter # : 988291   
1                          hpl nom for january 9 , 2001   
2                                          neon retreat   
3      photoshop , windows , office . cheap . main t...   
4                                   re : indian springs   
...                                                 ...   
5165   fw : crosstex energy , driscoll ranch # 1 , #...   
5166                               put the 10 on the ft   
5167                    3 / 4 / 2000 and following noms   
5169     industrial worksheets for august 2000 activity   
5170                     important online banking alert   

                                                   text  label  
0     \nthis is a follow up to the note i gave you o...      0  
1     \n( see attached file : hplnol 09 . xls )\n- h...      0  
2     \nho ho ho , we ' re around to that most wonde...      0  
3     \nabasements darer prudently fortuitous underg...      1  
4     \nthis deal is to book the teco pvr revenue . ...      0  
...                                                 ...    ...  
5165  \n9868\nplease note the following for april pr...      0  
5166  \nthe transport volumes decreased from 25000 t...      0  
5167  \nhpl can ' t take the extra 15 mmcf / d over ...      0  
5169  \nattached are the worksheets for august 2000 ...      0  
5170  \ndear valued citizensr bank member ,\ndue to ...      1  

[4993 rows x 3 columns]

#### 1st e word tokenize
##### puncuation remove
#### remove special char
#### remove stop word
#### Lemmatization
#### Label Encoder

In [9]:
from nltk.tokenize import word_tokenize
data['text'] = data['text'].fillna('') # nan(not a number) also kind of NONE type thing. ekhane amra oi value gula change kore dibo
data['text'].apply(lambda x: word_tokenize(x))


0       [this, is, a, follow, up, to, the, note, i, ga...
1       [(, see, attached, file, :, hplnol, 09, ., xls...
2       [ho, ho, ho, ,, we, ', re, around, to, that, m...
3       [abasements, darer, prudently, fortuitous, und...
4       [this, deal, is, to, book, the, teco, pvr, rev...
                              ...                        
5165    [9868, please, note, the, following, for, apri...
5166    [the, transport, volumes, decreased, from, 250...
5167    [hpl, can, ', t, take, the, extra, 15, mmcf, /...
5169    [attached, are, the, worksheets, for, august, ...
5170    [dear, valued, citizensr, bank, member, ,, due...
Name: text, Length: 4993, dtype: object

In [10]:
# remove punc
import string
def remove_punc(text):
  trans = str.maketrans('', '', string.punctuation)
  return text.translate(trans)

data['text'] = data['text'].apply(remove_punc)
data['text']

0       \nthis is a follow up to the note i gave you o...
1       \n see attached file  hplnol 09  xls \n hplnol...
2       \nho ho ho  we  re around to that most wonderf...
3       \nabasements darer prudently fortuitous underg...
4       \nthis deal is to book the teco pvr revenue  i...
                              ...                        
5165    \n9868\nplease note the following for april pr...
5166    \nthe transport volumes decreased from 25000 t...
5167    \nhpl can  t take the extra 15 mmcf  d over th...
5169    \nattached are the worksheets for august 2000 ...
5170    \ndear valued citizensr bank member \ndue to c...
Name: text, Length: 4993, dtype: object

In [11]:
### remove special char (abcd er baire habijabi)
import re
def remove_noise(text):
  t = re.sub('[^a-zA-Z]', ' ', text)
  return t
data['text'] = data['text'].apply(remove_noise)
data['text']

0        this is a follow up to the note i gave you on...
1         see attached file  hplnol     xls   hplnol  ...
2        ho ho ho  we  re around to that most wonderfu...
3        abasements darer prudently fortuitous undergo...
4        this deal is to book the teco pvr revenue  it...
                              ...                        
5165          please note the following for april prod...
5166     the transport volumes decreased from       to...
5167     hpl can  t take the extra    mmcf  d over the...
5169     attached are the worksheets for august      a...
5170     dear valued citizensr bank member  due to con...
Name: text, Length: 4993, dtype: object

In [12]:
### remove stop word
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

sw = stopwords.words('english')
def remove_sws(text):
    # low char
    text = text.lower()
    non_stop_word = []
    split_text = text.split()
    for new in split_text:
        if new not in sw:
            non_stop_word.append(new)
            # from nltk.stem import WordNetLemmatizer
            # lemmatizer = WordNetLemmatizer()
            # new = lemmatizer.lemmatize(new)
            # non_stop_word.append(new)
    return " ".join(non_stop_word)
            
# def remove_sws(text):
#   s = [word.lower() for word in text.split() if word.lower() not in sw]
#   return " ".join(s)
data['text'] = data['text'].apply(remove_sws)
data['text']

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\im087\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


0       follow note gave monday preliminary flow data ...
1                 see attached file hplnol xls hplnol xls
2       ho ho ho around wonderful time year neon leade...
3       abasements darer prudently fortuitous undergon...
4       deal book teco pvr revenue understanding teco ...
                              ...                        
5165    please note following april production regardi...
5166    transport volumes decreased contract thanks am...
5167    hpl take extra mmcf weekend try next week nom ...
5169    attached worksheets august activity three diff...
5170    dear valued citizensr bank member due concerns...
Name: text, Length: 4993, dtype: object

In [13]:
### Lemmatization
# similar word
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def lemma(text):
    
    lemmatize_Word = []
    split_text = text.split()
    for new in split_text:
        if new not in sw:
            lemmatize_Word.append(new)
            from nltk.stem import WordNetLemmatizer
            lemmatizer = WordNetLemmatizer()
            new = lemmatizer.lemmatize(new)
            lemmatize_Word.append(new)
    return " ".join(lemmatize_Word)
           
def lemma(text):
  l = [lemmatizer.lemmatize(word) for word in text.split()]
  return " ".join(l)

data['text'] = data['text'].apply(lemma)
data['text']

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\im087\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\im087\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\im087\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


0       follow note gave monday preliminary flow data ...
1                   see attached file hplnol xl hplnol xl
2       ho ho ho around wonderful time year neon leade...
3       abasement darer prudently fortuitous undergone...
4       deal book teco pvr revenue understanding teco ...
                              ...                        
5165    please note following april production regardi...
5166    transport volume decreased contract thanks ami...
5167    hpl take extra mmcf weekend try next week nom ...
5169    attached worksheet august activity three diffe...
5170    dear valued citizensr bank member due concern ...
Name: text, Length: 4993, dtype: object

In [14]:
### Label Encoder
# from sklearn.preprocessing import LabelEncoder
# encoder =LabelEncoder()

# data['v1']=encoder.fit_transform(data['v1'])
# data

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(max_features=3000)
x = tf.fit_transform(data['text']).toarray()
y = data['label']
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x)
from sklearn.naive_bayes import  MultinomialNB
# Create the instance of Naive Bayes
clf = MultinomialNB()
# Fit the data
clf.fit(X_train, y_train)
# Making prediction



y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:\n", classification_report(y_test, y_pred))



# your_sen = ["join the meeting"]
# your_sen = tf.transform(your_sen).toarray()
# y_pred = clf.predict(X_test)
# print(y_pred)
# print("Accuracy Score: ", accuracy_score(y_test, y_pred))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy: 94.09%
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96       732
           1       0.89      0.90      0.89       267

    accuracy                           0.94       999
   macro avg       0.92      0.93      0.92       999
weighted avg       0.94      0.94      0.94       999



In [23]:
def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    text = text.lower()  # Lowercase
    text = ''.join([char for char in text if char not in string.punctuation])  # Remove punctuation
    text = ' '.join([word for word in text.split() if word not in stop_words])  # Remove stopwords
    return text

# tokeize korte hobe
your_sen = ["join and love"]

# Preprocess the new sentence before vectorizing
your_sen = [preprocess_text(sen) for sen in your_sen]

# Transform the new sentence using the same vectorizer
your_sen_transformed = tf.transform(your_sen).toarray()
#data['v2'].apply(lambda x: word_tokenize(x))
# Predict the label for the new sentence
your_sen_pred = clf.predict(your_sen_transformed)

# Print the prediction for the new sentence
print("Prediction for your sentence:", 'Spam' if your_sen_pred[0] == 1 else 'Ham')







Prediction for your sentence: Spam
